name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta cada día a medianoche
  workflow_dispatch:  # Permite ejecución manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Usa la versión más reciente

      - name: Generate Snake Animation
        uses: Platane/snk@v3  # Asegúrate de usar la última versión
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake Animation
        uses: actions/upload-artifact@v4  # Actualiza a la última versión
        with:
          name: snake-animation
          path: dist

